// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQycW6UKNLIvKT9VzSHxB4LcdYyzOMdiQ',
    appId: '1:588711309496:web:583b66f0485c8dfb9d044d',
    messagingSenderId: '588711309496',
    projectId: 'go-to-your-home',
    authDomain: 'go-to-your-home.firebaseapp.com',
    storageBucket: 'go-to-your-home.firebasestorage.app',
    measurementId: 'G-VC5G6M85SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbD2w4PPHxeH_ZcVsij13wHGqZCuFtxHo',
    appId: '1:588711309496:android:48fe2831f2ebad4a9d044d',
    messagingSenderId: '588711309496',
    projectId: 'go-to-your-home',
    storageBucket: 'go-to-your-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitQjPPD1LEVtO5L98wpOcP02gXXaKjU8',
    appId: '1:588711309496:ios:3c33f4d3fcd613ee9d044d',
    messagingSenderId: '588711309496',
    projectId: 'go-to-your-home',
    storageBucket: 'go-to-your-home.firebasestorage.app',
    iosBundleId: 'com.example.goToYourHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAitQjPPD1LEVtO5L98wpOcP02gXXaKjU8',
    appId: '1:588711309496:ios:3c33f4d3fcd613ee9d044d',
    messagingSenderId: '588711309496',
    projectId: 'go-to-your-home',
    storageBucket: 'go-to-your-home.firebasestorage.app',
    iosBundleId: 'com.example.goToYourHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQycW6UKNLIvKT9VzSHxB4LcdYyzOMdiQ',
    appId: '1:588711309496:web:6ead9c275e8fa3c29d044d',
    messagingSenderId: '588711309496',
    projectId: 'go-to-your-home',
    authDomain: 'go-to-your-home.firebaseapp.com',
    storageBucket: 'go-to-your-home.firebasestorage.app',
    measurementId: 'G-FKFKVLJHKG',
  );
}
